name: Release Workflow

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js (required for Lerna)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run Lerna version
      - name: Bump version with Lerna
        run: npx lerna version minor --no-push -y
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Step 5: Create a new branch
      - name: Create release branch
        run: |
          BRANCH_NAME="release/${{ github.run_id }}"
          git checkout -b $BRANCH_NAME
          git add .
          git commit -m "chore: release version bump"
          git push origin $BRANCH_NAME

      # Step 6: Open a pull request
      - name: Create pull request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: release/${{ github.run_id }}
          base: main
          title: "Release: Version bump"
          body: "This PR includes the version bump generated by Lerna."
